#-------------------------------------------------------------------------------
# app.yaml
#
# Date: 2019-08-01
#
# Main configuration file for the application.
#-------------------------------------------------------------------------------
# Google App Engine environment
#-------------------------------------------------------------------------------
# We set the environment to standard since that is the only available
# environment for Python 3.7 (as of 2018-12-20)
env: standard
#-------------------------------------------------------------------------------
# Python runtime
#-------------------------------------------------------------------------------
runtime: python37
#-------------------------------------------------------------------------------