openapi: 3.0.0
servers:
  - url: /api/
info:
  title: REST API for ME
  version: '0.1'
paths:
  '/events.Sync':
    get:
      tags:
        - Events
      operationId: api.api.sync_events
      summary: Sync events for a specific service
      parameters:
        - name: service
          in: query
          schema:
            type: string
          description: The service you want to sync
      responses:
        '200':
          description: Returns how many new events there were synced and how many were updated
          content:
            application/json:
              schema:
                type: array
  '/feed.Get':
    get:
      tags:
        - Feed
      operationId: api.api.get_feed
      summary: Get all feeditems
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          description: The maximum number of items you want to get
        - name: page
          in: query
          schema:
            type: integer
          description: The pagenumber you want to retrieve
      responses:
        '200':
          description: Return feeditems
          content:
            application/json:
              schema:
                type: array
  '/templates.Get':
    get:
      tags:
        - Templates
      operationId: api.api.get_template
      summary: Get a template
      parameters:
        - name: template
          in: query
          schema:
            type: string
          description: The template you want to get
      responses:
        '200':
          description: Return template
          content:
            application/json:
              schema:
                type: array